# Default to Development Environment (Hot-Reloading)
# Use 'docker-compose -f docker-compose.prod.yml up' for production.
version: '3.8'

services:
  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres

  backend:
    extends:
      file: docker-compose.dev.yml
      service: backend

  gotenberg:
    extends:
      file: docker-compose.dev.yml
      service: gotenberg

  frontend:
    extends:
      file: docker-compose.dev.yml
      service: frontend

volumes:
  postgres_data_dev:


networks:
  applizor-network:
    driver: bridge
